### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation) make[1]: *** [NiuTrans.Decoder] Error 1 make: *** [all] Error 2

### ISSUE THREAD

**Issue by WUT-Post** [NiuTrans/NiuTrans.SMT#4]
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [NiuTrans.Decoder] Error 1
make: *** [all] Error 2

**Comment by xuchenneu** [comment]
We can't reproduce this error. Can you provide more information?
