### ISSUE TITLE
Error about "NiuTrans-running-segmenter"

### ISSUE THREAD

**Issue by multibla** [NiuTrans/NiuTrans.SMT#5]
some error occured when i run this script：
`perl NiuTrans-running-segmenter.pl \        # 中文预处理
        -lang   ch \
        -input  ../work/preprocessing/chinese.clean.txt \
        -output ../work/preprocessing/chinese.clean.txt.prepro \
        -method 01`

and some **error** info is as follows:

`########### SCRIPT ########### SCRIPT ############ SCRIPT ##########
#                                                                  #
# NiuTrans Running NiuSeg (version 1.2.0 Beta)    --www.nlplab.com #
#                                                                  #
########### SCRIPT ########### SCRIPT ############ SCRIPT ##########
Running: ../bin/NiuSegmenter_CN_x64 ../config/NiuTrans.NiuSeg.ch.config tmp.config.chi 11101
--- Initialize Chinese program ...
--- Chinese_Wrapper : Load configure file.
--- Chinese_Wrapper : Configure file load finished.
--- Chinese_Wrapper : Initialize segmentation ...
Reading keys from ../resource/Dict0920/len2.lex...
Sorting keys...
Analyzing ...
keys wcstok failed
##### Error ##### chi_LM-Based_word_breaker reports lex:../resource/Dict0920/len2.lex||||||loc:../resource/Dict0920/len2.loc||||||org:../resource/bi.org.dict||||||psn:../resource/Dict0920/len2.psn not found or can't open!
--- Chinese_Wrapper : Segmentations initialize finished.
--- Chinese_Wrapper : Initialize preprocessor ...
--- all_PreProcessing_FullToHalf stand ready.
--- Chinese_Wrapper : PreProcessors initialize finished.
--- Chinese_Wrapper : Initialize prev-recognizers ...
--- all_PrevRecognition_RegexRecognizer stand ready.
--- Chinese_Wrapper : Prev-recognizers initialize finished.
--- Chinese_Wrapper : Initialize post-recognizers ...
--- chi_All_Post_Details stand ready.
--- all_PostRecognition_MergeAtomToCompose stand ready.
--- Chinese_Wrapper : Post-recognizers initialize finished.
--- Chinese_Wrapper : Initialize translators ...
--- chi_Translation_ChinumToArabicnum stand ready.
--- chi_Translation_ArabicNumToEngTranslate stand ready.
--- chi_Translation_BilingualDictionary stand ready.
--- chi_Translation_NumberTranslator stand ready.
Error: Execution of: ../bin/NiuSegmenter_CN_x64 ../config/NiuTrans.NiuSeg.ch.config tmp.config.chi 11101
   die with signal 11, with coredump
`
**Environment**
Linux version 4.4.0-62-generic (buildd@lcy01-30) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) )

**Comment by liyinqiao2012** [comment]
Hi, sorry for late reply. Have you solved this issue?
If not, I'd like to help you. From your log, it seems len2.psn not found or can't open! You can check it first.
