### ISSUE TITLE
请问机器翻译中应该如何处理关于表情与特殊符号的问题

### ISSUE THREAD

**Issue by WIFIergege** [NiuTrans/NiuTrans.SMT#6]
在神经机器翻译中，我已经收集到不少数据，但是出现的问题是，中文到英文准确度可以保证，当设置平行语句时总会出问题，并且在训练过程中，日语和韩语这两种语言与中文的转换并不准确，韩语与日语中有很多语法与中文语法不同，所以想请教一下大佬们，有没有好的建议，还有就是在训练中，如果一句话中加入表情，那么识别语种会有问题，并且表情符号也会被吞掉，以上这几个问题请问有没有好的解决办法呢？

**Comment by libeineu** [comment]
感谢关注！针对您提出的问题我尝试进行回答一下，希望对您有所帮助：
（1）由于中英的语料比较丰富，因此其翻译质量相对较好。您提到日韩两种语言到中文的转换并不准确，这确实与语言之间的语法结构的差异有关，针对该问题可以通过扩大数据规模或增大模型容量来提高翻译质量，例如可以采用深层网络进行训练（训练集较充足的情况下）
（2）如果输入的句子中存在表情，而模型的训练语料中没用的话，会被当成UNK处理，甚至可能会被过滤掉，这样在翻译过程中会出现漏译的问题。针对该问题，可以考虑在训练数据中适当引入表情符号，可以一定程度上改善该问题。
如果有问题，欢迎交流，希望能帮助到您！

**Comment by WIFIergege** [comment]
@libeineu 方便加个微信吗？有些问题，还是想请教您一下，我的微信是：a15611851268，因为还有一些代码上的问题想请教您，不知道是否可以，我也是做这个相关的人，所以还是想请教像您这样的专业人士指点一下
