### ISSUE TITLE
Error: Execution of: ../bin/NiuSegmenter_CN_x64 ../config/NiuTrans.NiuSeg.ch.config tmp.config.chi 11101

### ISSUE THREAD

**Issue by KYRIEZX** [NiuTrans/NiuTrans.SMT#7]
My script:`perl NiuTrans-running-segmenter.pl -lang  ch -input  ../work/preprocessing/chinese.clean.txt -output ../work/preprocessing/chinese.clean.txt.prepro -method 01 `
But it turns to:
![image](https://user-images.githubusercontent.com/56826566/101148238-5a9a0f80-3658-11eb-8a82-dd03c56063fe.png)

**Comment by xuchenneu** [comment]
@KYRIEZX  We are so regretted that our word segmentation module can not run on the Ubuntu system due to some unsupported system-level functions. 
You can run it on the Centos system. If you don't have a Centos system available, you can segment the Chinese text with other tools, like Jieba.

**Comment by KYRIEZX** [comment]
> @KYRIEZX We are so regretted that our word segmentation module can not run on the Ubuntu system due to some unsupported system-level functions.
> You can run it on the Centos system. If you don't have a Centos system available, you can segment the Chinese text with other tools, like Jieba.

OK thanks.
